### PR TITLE
Remove options licenseUrl and requireLicenseAcceptance

### LINKED ISSUE #246: requireLicenseAcceptance option seems not working
**What version of `electron-installer-windows` are you using?**
1.1.0
**What version of `node` and `npm` are you using?**
npm 6.1.0
node v8.11.2
**What operating system are you using?**
windows7
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
yes
**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
I succeed to generate an installer for my app without option.
Now I'm trying to add a requireLicenseAcceptance .
For test purpose i tried : 
electron-installer-windows --src build/myapp-win32-x64/ --dest dist/ --licenseUrl https://github.com/squirrel/Squirrel.Windows/blob/master/COPYING  --requireLicenseAcceptance true
the installer is generated but..

**What did you expect to happen?**
i was expecting a prompt during launch of installer saying "please accept the license"
**What actually happened?**
the installer working well but without asking for license agreement.

### PR DESCRIPTION
**Pull request by fcastilloec**
Both options don't do anything and Squirrel doesn't seem to use them.

This sort of fixes #246

### CODE REVIEW

**Comment by fcastilloec** [comment]
They are legit options in the nuspec, but our code and Squirrel doesn't do anything about it (at least from the research I've done). @malept can you test if any of the two options do anything for you?
Other projects based on Squirrel don't have these options, here's an example of an issue about this https://github.com/electron/windows-installer/issues/212
Squirrel itself has no mention of these options anywhere in its docs.

The options are used (from what I've read, I might be wrong) only on nuget packages (`.nupkg`) which we do create. `licenseUrl` or `license` is usually used only on nuget.org and `requireLicenseAcceptance` seems to only work when installing the nuget package in Visual Studio. It seems Visual Studio has its own UI for this options and asking the user to accept the license. I can't verify this myself at the moment, this is only from some research I've done online. I know for a fact (I did test this myself) that these options don't do anything in the final `.exe`.

Unless somebody can verify my previous statement about `.nupkg`, we shouldn't add features that don't work as the user expect them, and that's why we had issue #246. If my previous statement is correct, we could modify our README to show that those options only work on nuget packages and not on the final `.exe` and also move to using the new `licese` option instead of `licenseUrl`

**Comment by malept** [comment]
I don't know anything about nuget/nuspec/nupkg other than the link I mentioned. If that's what you've found from your research, then get rid of it. You might want to major version bump though, it does remove two options.

**Comment by fcastilloec** [comment]
I'm going to try to verify my statement about Visual Studio this following week. In the meantime, I'll mark this PR as WIP. @malept can you add the WIP app to this repo?

**Comment by malept** [comment]
I added it but I don't think it will trigger until the PR changes somehow?

**Comment by fcastilloec** [comment]
I've confirmed with the developers of Windows.Squirrel, on their Slack channel, that both of these options do nothing at all on the final `.exe`. Here's the quote:

> No, it does nothing
Squirrel installers show no UI, if you want your users to accept a EULA, do it the first time your app starts

As I mentioned earlier, I'll do more research for the `.nupkg` side. Then we can decide if we're leaving the options and making a note that they work only on `.nupkg`, or just removed the options completely.

**Comment by fcastilloec** [comment]
After my research, I think we should remove the options. They do play a role on `.nupkg`, but they only work when installing on Visual Studio (or anything that requires a nuget feed).
Unless @malept has another take on this, I'll go ahead and merge

**Comment by malept** [comment]
I think this requires a major version bump because you're removing things?

**Comment by fcastilloec** [comment]
I usually would agree with that, removing features should be a major version bump, but in this case, the "features" we're removing never did anything, so technically we're not removing anything that somebody was able to use.
We don't have to release right away. I'm planning on submitting another PR for some checks on some required options, that we weren't doing.
My suggestion would be to do a new release when we also remove support for node 6 (in two weeks?), that way all `electron-installer-` modules will get the same bump

**Pull request merged**
