### PR TITLE
build: move CI from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by fcastilloec**
Hopefully, this switch might help with all the build errors that we're having with Travis and Appveyor.
~~This PR depends on having an npm token stored as `NPM_TOKEN` in this repo secrets, in order to publish the package to npm only when a new tag is pushed.~~

Also, this repo still shows check errors because `appveyor.yml` has been removed and it will need to be removed/uninstalled from the repo.

~~Both, adding the secret and~~ removing AppVeyor, need an administrator for them.

### CODE REVIEW

**Comment by fcastilloec** [comment]
It seems that if you have 2FA enabled, it's not possible to publish packages from a CI. I have admin access to this package on npm but I also have 2FA enabled. Maybe the best thing would be to stop releasing versions from the CI and instead publish directly from our machines. We still have to submit a PR for any new version, so once approved, either of us that created the PR and tag, can push the new version.

**Comment by malept** [comment]
There's another way, but there's some setup involved and we probably don't want to do this due to the overhead. The Ecosystem WG uses a system called [CFA (continuous factor authentication)](https://github.com/continuousauth/web#readme) to publish new releases of most of the tools overseen by the WG by having `semantic-release`-driven releases, with the OTP token given by a WG member to a Slack bot, which passes it to the CI worker that performs the release.

**Comment by fcastilloec** [comment]
@malept I was also thinking of migrating the tests to AVA instead of mocha but I'm not sure if that will help. Hopefully, the move to Github Actions is enough. Any thoughts about migrating to AVA?

**Comment by malept** [comment]
> I was also thinking of migrating the tests to AVA instead of mocha but I'm not sure if that will help. Hopefully, the move to Github Actions is enough. Any thoughts about migrating to AVA?

Feel free, although it's not clear to me what problem you're trying to solve.

**Comment by fcastilloec** [comment]
> Feel free, although it's not clear to me what problem you're trying to solve.

Our builds tend to fail randomly, and a restart usually fixes it. It usually gets with a timeout error. I'm not sure if this was a problem with the CI we were using, or the testing framework, or both. So, I hope that switching the CI is good enough, we haven't had enough commits to test, but if the problem continues, maybe switching to AVA might help.

**Comment by malept** [comment]
I'd bet that it was due to the CI platform rather than the test framework, but we'll see.

**Pull request merged**
