### PR TITLE
Update npm key

### PR DESCRIPTION
**Pull request by unindented**
@fcastilloec could you please review?

### CODE REVIEW

**Comment by malept** [comment]
Did you redo the AppVeyor PR build? The AppVeyor push build looks like it passed.

**Comment by fcastilloec** [comment]
Yes, I had to restart the PR build. Both tests in AppVeyor have passed now: [branch](https://ci.appveyor.com/project/unindented/electron-installer-windows/builds/19347509) and [PR](https://ci.appveyor.com/project/unindented/electron-installer-windows/builds/19348441) but that is not being shown in GitHub, they are still pointing to 'unindented' repo (which doesn't exist anymore).
Travis seems to have worked for the PR but the branch/push is pointing to `unindented` repos.

**Comment by malept** [comment]
I'm just going to call this good and merge it unless you have any objections @fcastilloec

**Comment by fcastilloec** [comment]
No objections, go ahead and merge

**Pull request merged**
